"""Turning a finished run into the five things people actually leave with.

The panel is written as parquet during ageing because that is the right working
format. It is rarely the right *leaving* format: a risk team wants a CSV, an
analyst wants an Excel sheet, an auditor wants the spec and the validation
report. Each function here converts once, on request, and caches the result next
to the run so a second click is instant.

The validation report is deliberately a standalone HTML file with no external
assets. It is the artefact that gets emailed, attached to a ticket, or filed
against a model-risk review, and any of those turn a CDN link into a broken page.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

import pandas as pd

# Excel's hard limit is 1,048,576 rows including the header. Writing right up to
# it produces a file that opens with a warning, so the cap is the round number
# below and the truncation is stated in the file itself.
EXCEL_ROW_LIMIT = 1_000_000

FORMATS = ("csv", "parquet", "xlsx", "yaml", "report")

MEDIA_TYPES = {
    "csv": "text/csv",
    "parquet": "application/octet-stream",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "yaml": "application/x-yaml",
    "report": "text/html",
}


class ExportError(RuntimeError):
    """The requested export cannot be produced."""


def export(
    fmt: str,
    *,
    # The configuration and the report describe a run rather than reformatting
    # its data, so neither needs the panel.
    panel: str | Path | None = None,
    spec: dict[str, Any] | None = None,
    result: dict[str, Any] | None = None,
    out_dir: str | Path,
    stem: str = "synthetic_data",
) -> Path:
    """Produce one downloadable artefact and return the path to it."""
    if fmt not in FORMATS:
        raise ExportError(f"unknown format {fmt!r}; expected one of {', '.join(FORMATS)}")

    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)

    if fmt == "yaml":
        return _write_yaml(spec, directory / f"{stem}.yaml")
    if fmt == "report":
        return _write_report(spec, result, directory / f"{stem}_validation.html")

    if panel is None:
        raise ExportError("this run produced no panel to export")
    source = Path(panel)
    if not source.exists():
        raise ExportError(f"the panel file is missing: {source.name}")

    if fmt == "parquet":
        return source

    target = directory / f"{stem}.{fmt}"
    if target.exists() and target.stat().st_mtime >= source.stat().st_mtime:
        return target

    frame = pd.read_parquet(source)
    if fmt == "csv":
        frame.to_csv(target, index=False)
    else:
        _write_excel(frame, target, result)
    return target


def _write_yaml(spec: dict[str, Any] | None, target: Path) -> Path:
    import yaml

    if not spec:
        raise ExportError("no spec was recorded for this run")
    header = (
        "# Synthetic Data Designer — the configuration that produced this dataset.\n"
        "# Re-run it with:  sdd run this-file.yaml --records N --out ./out\n"
    )
    body = yaml.safe_dump(spec, sort_keys=False, allow_unicode=True, width=100)
    target.write_text(f"{header}\n{body}", encoding="utf-8")
    return target


def _write_excel(frame: pd.DataFrame, target: Path, result: dict[str, Any] | None) -> Path:
    """Write the panel to a sheet, with a second sheet saying where it came from."""
    truncated = len(frame) > EXCEL_ROW_LIMIT
    body = frame.head(EXCEL_ROW_LIMIT) if truncated else frame

    with pd.ExcelWriter(target, engine="openpyxl") as writer:
        body.to_excel(writer, sheet_name="data", index=False)
        notes = _provenance_rows(result)
        if truncated:
            notes.append(
                (
                    "Truncated",
                    f"{len(frame):,} rows generated; {EXCEL_ROW_LIMIT:,} written. "
                    "Excel cannot hold more — download CSV or parquet for the whole panel.",
                )
            )
        pd.DataFrame(notes, columns=["Field", "Value"]).to_excel(
            writer, sheet_name="about", index=False
        )
    return target


def _provenance_rows(result: dict[str, Any] | None) -> list[tuple[str, str]]:
    if not result:
        return [("Generated by", "Synthetic Data Designer")]
    timings = result.get("timings") or {}
    validation = result.get("validation") or {}
    return [
        ("Generated by", "Synthetic Data Designer"),
        ("Spec", str(result.get("spec", ""))),
        ("Spec hash", str(result.get("spec_hash", ""))),
        ("Generation method", str(result.get("method", ""))),
        ("Seed", str(result.get("seed", ""))),
        ("Entities", f"{result.get('entities', 0):,}"),
        ("Periods", str(result.get("periods", ""))),
        ("Scenario", str(result.get("scenario") or "none")),
        ("Seconds", str(timings.get("total_seconds", ""))),
        (
            "Validation",
            "passed"
            if validation.get("passed")
            else f"{validation.get('failed', 0)} check(s) failed",
        ),
    ]


# ---------------------------------------------------------------------------
# the validation report
# ---------------------------------------------------------------------------


def _write_report(spec: dict[str, Any] | None, result: dict[str, Any] | None, target: Path) -> Path:
    if not result:
        raise ExportError("no run was recorded, so there is nothing to report on")
    target.write_text(report_html(spec, result), encoding="utf-8")
    return target


def report_html(spec: dict[str, Any] | None, result: dict[str, Any]) -> str:
    """A standalone validation report: what ran, what was checked, what failed."""
    validation = result.get("validation") or {}
    checks = validation.get("checks", [])
    passed = [c for c in checks if c.get("passed")]
    failed = [c for c in checks if not c.get("passed")]

    verdict = "PASSED" if validation.get("passed") else "FAILED"
    verdict_class = "ok" if validation.get("passed") else "bad"

    rows = "".join(
        f"<tr class='{'ok' if c.get('passed') else 'bad'}'>"
        f"<td>{'pass' if c.get('passed') else 'FAIL'}</td>"
        f"<td><code>{html.escape(str(c.get('name', '')))}</code></td>"
        f"<td>{html.escape(str(c.get('description') or ''))}</td>"
        f"<td class='num'>{c.get('violations', 0):,}</td>"
        f"<td>{html.escape(str(c.get('error') or ''))}</td></tr>"
        for c in failed + passed
    )

    mix = result.get("mix") or []
    mix_rows = ""
    if mix:
        keys = [k for k in mix[0] if k not in ("period", "date", "rows")]
        header = "".join(f"<th class='num'>{html.escape(k)}</th>" for k in keys)
        mix_rows = (
            "<h2>Pool composition</h2><table><thead><tr><th>Cut-off</th>"
            f"<th class='num'>Rows</th>{header}</tr></thead><tbody>"
            + "".join(
                "<tr><td>"
                + html.escape(str(period.get("date", "")))
                + f"</td><td class='num'>{period.get('rows', 0):,}</td>"
                + "".join(f"<td class='num'>{period.get(k, 0):,}</td>" for k in keys)
                + "</tr>"
                for period in mix
            )
            + "</tbody></table>"
        )

    facts = "".join(
        f"<div class='fact'><div class='k'>{html.escape(k)}</div>"
        f"<div class='v'>{html.escape(str(v))}</div></div>"
        for k, v in _provenance_rows(result)
        if v
    )

    generation = result.get("generation_notes") or {}
    randomness = generation.get("randomness") or {}
    randomness_note = ""
    if randomness:
        randomness_note = (
            "<h2>Randomness applied</h2><p>"
            + ", ".join(
                f"{value} column(s) {label}"
                for label, value in (
                    (
                        "reordered to match the sample's correlation",
                        randomness.get("correlated", 0),
                    ),
                    ("given outliers", randomness.get("outliers", 0)),
                    ("jittered", randomness.get("noised", 0)),
                    ("blanked", randomness.get("blanked", 0)),
                )
                if value
            )
            + ".</p>"
        )

    spec_json = html.escape(json.dumps(spec, indent=2)[:200_000]) if spec else ""

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>Validation report — {html.escape(str(result.get("spec", "")))}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 14px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0 auto; padding: 40px 28px 80px; max-width: 1000px; color: #1b1b1f; }}
  h1 {{ font-size: 22px; margin: 0 0 4px; }}
  h2 {{ font-size: 15px; margin: 32px 0 10px; padding-bottom: 6px; border-bottom: 1px solid #e2e2e6; }}
  .verdict {{ display: inline-block; padding: 3px 10px; border-radius: 4px; font-weight: 600;
              letter-spacing: .04em; font-size: 12px; }}
  .verdict.ok {{ background: #e4f3ea; color: #1d6b3f; }}
  .verdict.bad {{ background: #fbe6e6; color: #96231f; }}
  .facts {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
            gap: 10px; margin-top: 18px; }}
  .fact {{ border: 1px solid #e2e2e6; border-radius: 6px; padding: 9px 11px; }}
  .fact .k {{ font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #6b6b73; }}
  .fact .v {{ font-size: 14px; margin-top: 2px; font-variant-numeric: tabular-nums; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
  th, td {{ text-align: left; padding: 6px 9px; border-bottom: 1px solid #ececf0; vertical-align: top; }}
  th {{ font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #6b6b73; }}
  td.num, th.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  tr.bad td:first-child {{ color: #96231f; font-weight: 600; }}
  tr.ok td:first-child {{ color: #1d6b3f; }}
  code {{ font: 12px ui-monospace, SFMono-Regular, Menlo, monospace; }}
  pre {{ background: #f6f6f8; padding: 14px; border-radius: 6px; overflow: auto; font-size: 12px;
         max-height: 460px; }}
  footer {{ margin-top: 40px; color: #6b6b73; font-size: 12px; }}
  @media (prefers-color-scheme: dark) {{
    body {{ color: #e6e6ea; background: #16161a; }}
    h2, th, td {{ border-color: #2c2c33; }}
    .fact {{ border-color: #2c2c33; }}
    pre {{ background: #1e1e24; }}
  }}
</style></head>
<body>
<h1>Validation report</h1>
<p><span class="verdict {verdict_class}">{verdict}</span>
  &nbsp;{len(passed)} of {len(checks)} checks passed.</p>

<div class="facts">{facts}</div>

<h2>Invariants</h2>
<p>Each check is derived from the spec itself — what it declares static, terminal, bounded or
   pinned to a state — and run as a query against the generated panel. Zero violating rows
   means the data does what the spec says it does.</p>
<table><thead><tr><th>Result</th><th>Check</th><th>What it asserts</th>
  <th class="num">Violations</th><th>Error</th></tr></thead>
<tbody>{rows or "<tr><td colspan='5'>No checks ran.</td></tr>"}</tbody></table>

{randomness_note}
{mix_rows}

<h2>Configuration</h2>
<pre>{spec_json or "The spec was not recorded with this run."}</pre>

<footer>Generated by Synthetic Data Designer. This report is self-contained — no external
assets, no scripts.</footer>
</body></html>
"""
